//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProeryValue
    {
        public System.Guid Id { get; set; }
        public string ValueData { get; set; }
        public string SortOrder { get; set; }
        public string Status { get; set; }
    
        public virtual CategoryProery CategoryProery { get; set; }
    }
}
