//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CreditCards = new HashSet<CreditCard>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string CreateDate { get; set; }
    
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
