//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    
    public enum OrderStatus : int
    {
        Closed = 1,
        Created = 2,
        Shipped = 3,
        Returned = 4,
        Cancelled = 5
    }
}
