//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal SalePrice { get; set; }
        public decimal PurchasePrice { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual Category Category { get; set; }
        public virtual OrderContract OrderContract { get; set; }
    }
}
